apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: mynginx-ingress
spec:
  rules:
    - host: user10.netapp.local
      http:
        paths:
          - backend:
              serviceName: mynginx
              servicePort: 80
            path: /
